#!/usr/bin/env python3
"""TypeScript/Express test generation for the verification gate.

Generates a `node --test` file that imports the real handler, calls it with a
mock request and response, and asserts what the *specification* promises. Same
contract as the Go generator in verify.py: the test is written to fail when the
claim is true, so a passing test refutes the claim.

The mock is dependency-free by design. A gate that needs supertest installed can
only verify projects that already have it, and a gate that cannot run is a gate
that lets claims through unchecked.
"""

from __future__ import annotations

import json

# One mock, shared by every generated test. It implements the slice of the
# Express response API that handlers actually use to produce a contract:
# status/json/send/set/get, and the chaining they rely on.
HARNESS = """// Generated by auditor/verify_ts.py to test one claim. Regenerated per claim;
// not intended to be committed.
import { test } from "node:test";
import assert from "node:assert/strict";

function mockRequest({ method, params = {}, query = {}, headers = {}, body = undefined }) {
  const lower = Object.fromEntries(
    Object.entries(headers).map(([k, v]) => [k.toLowerCase(), v]));
  return {
    method, params, query, body,
    headers: lower,
    get: (name) => lower[String(name).toLowerCase()],
    header: (name) => lower[String(name).toLowerCase()],
    is: () => false,
    accepts: () => true,
  };
}

function mockResponse() {
  const res = {
    statusCode: 200,
    body: undefined,
    headers: {},
    finished: false,
    status(code) { this.statusCode = code; return this; },
    set(name, value) {
      if (typeof name === "object") Object.assign(this.headers, name);
      else this.headers[String(name).toLowerCase()] = value;
      return this;
    },
    header(name, value) { return this.set(name, value); },
    get(name) { return this.headers[String(name).toLowerCase()]; },
    type() { return this; },
    json(payload) { this.body = payload; this.finished = true; return this; },
    send(payload) { this.body = payload; this.finished = true; return this; },
    end() { this.finished = true; return this; },
  };
  return res;
}

// A list endpoint is described by the shape of its elements, so unwrap a
// top-level array before inspecting fields.
function firstObject(value) {
  if (Array.isArray(value)) return value.length ? value[0] : null;
  if (value && typeof value === "object") return value;
  return null;
}

function jsonType(value) {
  if (value === null) return "null";
  if (Array.isArray(value)) return "array";
  if (typeof value === "number") return "number";
  if (typeof value === "string") return "string";
  if (typeof value === "boolean") return "boolean";
  if (typeof value === "object") return "object";
  return "null";
}

async function invoke(handler, req) {
  const res = mockResponse();
  await handler(req, res, (err) => { if (err) throw err; });
  return res;
}
"""


def render_test(claim, operation, module_path, handler, request, success_code, documented,
                documented_header=None):
    """Emit the whole test file for one claim."""
    kind = claim["kind"]
    detail = claim.get("detail", "")
    lit = json.dumps

    setup = f"""import {{ {handler} }} from {lit("./" + module_path)};

test({lit(kind + " on " + claim["method"].upper() + " " + claim["path"])}, async () => {{
  const req = mockRequest({json.dumps(request, indent=2)});
  const res = await invoke({handler}, req);
"""

    if kind == "status_code_mismatch":
        body = f"""  assert.equal(res.statusCode, {success_code},
    `spec documents {success_code} on success; handler returned ${{res.statusCode}}`);"""

    elif kind == "response_field_mismatch":
        body = f"""  const obj = firstObject(res.body);
  assert.ok(obj, `response is not a JSON object: ${{JSON.stringify(res.body)}}`);
  assert.ok({lit(detail)} in obj,
    `spec documents field {lit(detail)}; response carries ${{JSON.stringify(Object.keys(obj).sort())}}`);"""

    elif kind == "response_type_mismatch":
        expected = documented.get(detail, {}).get("type", "string")
        body = f"""  const obj = firstObject(res.body);
  assert.ok(obj, `response is not a JSON object: ${{JSON.stringify(res.body)}}`);
  assert.ok({lit(detail)} in obj, `field {lit(detail)} absent from response`);
  assert.equal(jsonType(obj[{lit(detail)}]), {lit(expected)},
    `spec declares {lit(detail)} as {expected}; response carries ${{jsonType(obj[{lit(detail)}])}} (${{obj[{lit(detail)}]}})`);"""

    elif kind == "response_header_mismatch":
        # The probe must assert the header the *specification* names. The
        # claim's detail carries the header the code sets, and asserting that
        # tests the drift instead of the promise: the header is present, the
        # test passes, and a true finding is refuted.
        expected_header = documented_header or detail
        body = f"""  assert.ok(res.get({lit(expected_header)}),
    `documentation names header {expected_header}; response sent ${{JSON.stringify(Object.keys(res.headers))}}`);"""

    elif kind == "auth_mismatch":
        body = """  assert.ok(res.statusCode !== 401 && res.statusCode !== 403,
    `spec documents this endpoint as public; unauthenticated request returned ${res.statusCode}`);"""

    elif kind == "request_required_mismatch":
        body = f"""  assert.ok(res.statusCode < 400 || res.statusCode >= 500,
    `spec does not require {lit(detail)}, but omitting it returned ${{res.statusCode}}: ${{JSON.stringify(res.body)}}`);"""

    elif kind == "validation_mismatch":
        body = f"""  assert.ok(res.statusCode < 400 || res.statusCode >= 500,
    `value for {lit(detail)} satisfies the documented constraint, but the handler returned ${{res.statusCode}}: ${{JSON.stringify(res.body)}}`);"""

    elif kind == "default_value_mismatch":
        default = documented.get("__default__")
        body = f"""  const obj = firstObject(res.body);
  assert.ok(obj, `response is not a JSON object: ${{JSON.stringify(res.body)}}`);
  if (!({lit(detail)} in obj)) {{
    return; // default not observable in the response; reported as unsupported
  }}
  assert.equal(obj[{lit(detail)}], {json.dumps(default)},
    `spec documents a default of {default} for {lit(detail)}; handler applied ${{obj[{lit(detail)}]}}`);"""
    else:
        raise ValueError(f"unsupported claim kind for TypeScript: {kind}")

    return HARNESS + "\n" + setup + body + "\n});\n"
