#!/usr/bin/env python3
"""PHP/Laravel test generation for the verification gate.

Emits a standalone PHP script that includes the controller, calls the method
directly, and asserts what the *specification* promises. Run with `php`, no
PHPUnit: a gate that needs a test framework installed can only verify projects
that already have one.

The controller is called directly rather than through the framework's HTTP kernel
for the same reason the other gates avoid their frameworks - `vendor/` may not be
installed, and a gate that cannot run is a gate that lets claims through. Two
return conventions are accepted:

    return [201, [...]];        explicit status and body
    return [...];               body only; status from the route declaration
"""

from __future__ import annotations

import json

HARNESS = '''<?php
/**
 * Generated by auditor/verify_php.py to test one claim. Regenerated per claim;
 * not intended to be committed.
 */
declare(strict_types=1);

function fail(string $message): void
{
    echo "ASSERTION: {$message}\\n";
    exit(1);
}

/**
 * Normalise a controller return into [status, body].
 *
 * A two-element list whose first entry is an integer is the explicit form.
 * Anything else is the body, and the status is whatever the route declared.
 */
function unwrap($result, int $declared): array
{
    if (is_array($result) && count($result) === 2 && array_is_list($result) && is_int($result[0])) {
        return [$result[0], $result[1]];
    }
    return [$declared, $result];
}

/** A list endpoint is described by the shape of its elements. */
function firstObject($value)
{
    if (is_array($value) && array_is_list($value)) {
        return $value === [] ? null : (is_array($value[0]) ? $value[0] : null);
    }
    return is_array($value) ? $value : null;
}

function jsonType($value): string
{
    if (is_bool($value)) return "boolean";
    if (is_int($value) || is_float($value)) return "number";
    if (is_string($value)) return "string";
    if (is_null($value)) return "null";
    if (is_array($value)) return array_is_list($value) ? "array" : "object";
    return "null";
}
'''


def php_literal(value):
    """Render a Python value as a PHP literal.

    JSON is not PHP: an object is `{"a": 1}` in one and `['a' => 1]` in the
    other, so emitting JSON produced a parse error rather than a verdict. Scalars
    and lists happen to coincide, which is exactly why this was easy to miss.
    """
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(php_literal(v) for v in value) + "]"
    if isinstance(value, dict):
        return "[" + ", ".join(f"{php_literal(k)} => {php_literal(v)}"
                               for k, v in value.items()) + "]"
    return "null"


def render_test(claim, operation, controller_file, controller_class, method,
                args, success_code, documented, declared_status=None):
    kind = claim["kind"]
    detail = claim.get("detail", "")
    lit = json.dumps
    declared = declared_status or success_code

    setup = f'''
require_once __DIR__ . "/" . {lit(controller_file)};

$controller = new {controller_class}();
[$status, $body] = unwrap($controller->{method}(...{php_literal(args)}), {declared});
'''

    if kind == "status_code_mismatch":
        body = f'''
if ($status !== {success_code}) {{
    fail("spec documents {success_code} on success; handler returned {{$status}}");
}}
'''
    elif kind == "response_field_mismatch":
        body = f'''
$obj = firstObject($body);
if ($obj === null) fail("response is not an object: " . json_encode($body));
if (!array_key_exists({lit(detail)}, $obj)) {{
    fail("spec documents field {detail}; response carries " . json_encode(array_keys($obj)));
}}
'''
    elif kind == "response_type_mismatch":
        expected = documented.get(detail, {}).get("type", "string")
        body = f'''
$obj = firstObject($body);
if ($obj === null) fail("response is not an object: " . json_encode($body));
if (!array_key_exists({lit(detail)}, $obj)) fail("field {detail} absent from response");
$got = jsonType($obj[{lit(detail)}]);
if ($got !== {lit(expected)}) {{
    fail("spec declares {detail} as {expected}; response carries {{$got}} (" . json_encode($obj[{lit(detail)}]) . ")");
}}
'''
    elif kind in ("request_required_mismatch", "validation_mismatch"):
        subject = (f"spec does not require {detail}, but omitting it"
                   if kind == "request_required_mismatch"
                   else f"value for {detail} satisfies the documented constraint, but the handler")
        body = f'''
if ($status >= 400 && $status < 500) {{
    fail("{subject} returned {{$status}}: " . json_encode($body));
}}
'''
    elif kind == "default_value_mismatch":
        default = documented.get("__default__")
        body = f'''
$obj = firstObject($body);
if ($obj === null) fail("response is not an object: " . json_encode($body));
if (!array_key_exists({lit(detail)}, $obj)) {{
    echo "SKIP: response does not echo {detail}\\n";
    exit(0);
}}
if ($obj[{lit(detail)}] != {php_literal(default)}) {{
    fail("spec documents a default of {default} for {detail}; handler applied " . json_encode($obj[{lit(detail)}]));
}}
'''
    elif kind == "auth_mismatch":
        body = '''
if ($status === 401 || $status === 403) {
    fail("spec documents this endpoint as public; unauthenticated request returned {$status}");
}
'''
    else:
        raise ValueError(f"unsupported claim kind for PHP: {kind}")

    return HARNESS + setup + body + '\necho "OK\\n";\n'
