#!/usr/bin/env python3
"""Python test generation for the verification gate.

Emits a standalone script that imports the real handler, calls it, and asserts
what the *specification* promises. Run with `python3`, no pytest: a gate that
needs a test framework installed can only verify projects that already have one.

Handlers are called directly rather than through a test client, so the target
project's web framework need not be installed. Three return conventions are
accepted, because real projects use all of them:

    return 201, {...}        explicit status and body
    return {...}             body only; status comes from the decorator
    raise SomeHttpError      an exception carrying .status or .status_code
"""

from __future__ import annotations

import json

HARNESS = '''#!/usr/bin/env python3
"""Generated by auditor/verify_py.py to test one claim. Regenerated per claim;
not intended to be committed."""

import json
import sys


def fail(message):
    print("ASSERTION: " + message)
    sys.exit(1)


def unwrap(result, declared_status):
    """Normalise a handler return into (status, body).

    A 2-tuple of (int, payload) is the explicit form. Anything else is the body,
    and the status is whatever the route decorator declared.
    """
    if isinstance(result, tuple) and len(result) == 2 and isinstance(result[0], int):
        return result[0], result[1]
    return declared_status, result


def call(handler, kwargs, declared_status):
    """Invoke the handler, translating an HTTP-shaped exception into a status
    rather than letting it abort the check - a 400 is an answer, not a crash."""
    import asyncio
    import inspect
    try:
        if inspect.iscoroutinefunction(handler):
            result = asyncio.run(handler(**kwargs))
        else:
            result = handler(**kwargs)
    except Exception as exc:
        status = getattr(exc, "status", None) or getattr(exc, "status_code", None)
        if status is None:
            raise
        return int(status), {"error": str(exc)}
    return unwrap(result, declared_status)


def first_object(value):
    """A list endpoint is described by the shape of its elements."""
    if isinstance(value, list):
        return value[0] if value else None
    if isinstance(value, dict):
        return value
    return None


def _stub_framework(name):
    """Install a no-op stand-in for a web framework that is not installed.

    A route module imports its framework at the top, so without this the probe
    dies on ModuleNotFoundError before it reaches the handler - and an
    environment problem would read as a failed verification. The stub only ever
    fills in for a framework that is genuinely absent; where the real one is
    installed it is imported normally and used.

    Decorators return the function unchanged, which is all the gate needs: it
    calls the handler directly and takes the status from the route table.
    """
    import types

    def _decorator(*_a, **_k):
        def wrap(fn):
            return fn
        return wrap

    class _Router:
        def __init__(self, *_a, **_k):
            pass

        def __getattr__(self, _name):
            return _decorator

    module = types.ModuleType(name)
    for symbol in ("APIRouter", "FastAPI", "Flask", "Blueprint", "Depends",
                   "Request", "Response", "HTTPException", "Query", "Path", "Body",
                   "Header", "Form", "File", "UploadFile", "status", "BackgroundTasks"):
        setattr(module, symbol, _Router)
    module.__getattr__ = lambda _n: _Router
    sys.modules[name] = module
    return module


def ensure_importable(module_path, frameworks=("fastapi", "flask", "starlette",
                                               "pydantic", "sqlalchemy")):
    """Import the handler's module, stubbing absent frameworks as needed."""
    import importlib
    for _ in range(len(frameworks) + 1):
        try:
            return importlib.import_module(module_path)
        except ModuleNotFoundError as exc:
            missing = (exc.name or "").split(".")[0]
            if not missing or missing in sys.modules:
                raise
            _stub_framework(missing)
    return importlib.import_module(module_path)


def json_type(value):
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, (int, float)):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, list):
        return "array"
    if isinstance(value, dict):
        return "object"
    return "null"
'''


def render_test(claim, operation, module_path, handler, kwargs, success_code, documented,
                declared_status=None):
    """`success_code` is what the spec promises; `declared_status` is what the
    route decorator says. They must stay separate: unwrapping the handler's
    return with the spec's status would make a status mismatch undetectable,
    because the probe would assert the very number it assumed."""

    kind = claim["kind"]
    detail = claim.get("detail", "")
    lit = json.dumps

    module = module_path.replace("/", ".").removesuffix(".py")
    fallback_status = declared_status or success_code
    setup = f'''
sys.path.insert(0, ".")
_module = ensure_importable({lit(module)})
{handler} = getattr(_module, {lit(handler)})

status, body = call({handler}, {json.dumps(kwargs)}, {fallback_status})
'''

    if kind == "status_code_mismatch":
        body = f'''
if status != {success_code}:
    fail("spec documents {success_code} on success; handler returned %d" % status)
'''
    elif kind == "response_field_mismatch":
        body = f'''
obj = first_object(body)
if obj is None:
    fail("response is not a JSON object: %r" % (body,))
if {lit(detail)} not in obj:
    fail("spec documents field {detail}; response carries %r" % (sorted(obj),))
'''
    elif kind == "response_type_mismatch":
        expected = documented.get(detail, {}).get("type", "string")
        body = f'''
obj = first_object(body)
if obj is None:
    fail("response is not a JSON object: %r" % (body,))
if {lit(detail)} not in obj:
    fail("field {detail} absent from response")
got = json_type(obj[{lit(detail)}])
if got != {lit(expected)}:
    fail("spec declares {detail} as {expected}; response carries %s (%r)" % (got, obj[{lit(detail)}]))
'''
    elif kind in ("request_required_mismatch", "validation_mismatch"):
        subject = ("spec does not require {0}, but omitting it".format(detail)
                   if kind == "request_required_mismatch"
                   else "value for {0} satisfies the documented constraint, but the handler".format(detail))
        body = f'''
if 400 <= status < 500:
    fail("{subject} returned %d: %r" % (status, body))
'''
    elif kind == "default_value_mismatch":
        default = documented.get("__default__")
        body = f'''
obj = first_object(body)
if obj is None:
    fail("response is not a JSON object: %r" % (body,))
if {lit(detail)} not in obj:
    print("SKIP: response does not echo {detail}; default not observable here")
    sys.exit(0)
if obj[{lit(detail)}] != {json.dumps(default)}:
    fail("spec documents a default of {default} for {detail}; handler applied %r" % (obj[{lit(detail)}],))
'''
    elif kind == "auth_mismatch":
        body = '''
if status in (401, 403):
    fail("spec documents this endpoint as public; unauthenticated request returned %d" % status)
'''
    elif kind == "undocumented_status":
        body = f'''
if status == {detail or 0}:
    fail("handler returned %d, which the spec does not document" % status)
'''
    else:
        raise ValueError(f"unsupported claim kind for Python: {kind}")

    return HARNESS + setup + body + '\nprint("OK")\n'
